<?php
$title = 'Products';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th></th>
    <th>Name</th>
    <th>Slug</th>
    <th>&nbsp;</th>
</tr>
<?php $index = 0; ?>
<?php foreach ($this->products as $product) : ?>
    <?php $index++; ?>
    <tr>
        <td><?php echo $this->integerToRomanNumeral($index) ?></td>
        <td><?php echo $this->escapeHtml($product->getTitle());?></td>
        <td><?php echo $this->escapeHtml($product->getSlug());?></td>
        <td>
            <a href="<?php echo $this->url('shop/product/edit',
                array('id' => $product->getId()));?>">Edit</a>
                            
            <a href="<?php echo $this->url('shop/product/delete',
                array('id' => $product->getId()));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>